fix: sed

diff --git a/.github/workflows/update-version-header.yml b/.github/workflows/update-version-header.yml
--- a/.github/workflows/update-version-header.yml
+++ b/.github/workflows/update-version-header.yml
@@ -41,8 +41,12 @@ jobs:
           sed -i 's/#define VERSION_PATCH [0-9]*/#define VERSION_PATCH '"$PATCH"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h
           if [ $? -eq 0 ]; then echo "VERSION_PATCH updated successfully"; else echo "Failed to update VERSION_PATCH"; fi
 
-          sed -i 's/"Version": "[0-9]*.[0-9]*.[0-9]*"/"Version": "'"$VERSION"'"/' ScooterUtils.uplugin
+          echo "sed -i 's/"Version": [0-9]*.[0-9]*.[0-9]*/"Version": '"$VERSION"'/' ScooterUtils.uplugin"
+          sed -i 's/"Version": [0-9]*.[0-9]*.[0-9]*/"Version": '"$VERSION"'/' ScooterUtils.uplugin
+          if [ $? -eq 0 ]; then echo "uplugin Version updated successfully"; else echo "Failed to update uplugin Version"; fi
+          echo "sed -i 's/"VersionName": "[0-9]*.[0-9]*.[0-9]*"/"Version": "'"$VERSION"'"/' ScooterUtils.uplugin"
           sed -i 's/"VersionName": "[0-9]*.[0-9]*.[0-9]*"/"Version": "'"$VERSION"'"/' ScooterUtils.uplugin
+          if [ $? -eq 0 ]; then echo "uplugin VersionName updated successfully"; else echo "Failed to update upluginVersionName"; fi
        
           
           # Print the contents of the header file after updating
