fix: trying for version

diff --git a/.github/workflows/update-version-header.yml b/.github/workflows/update-version-header.yml
--- a/.github/workflows/update-version-header.yml
+++ b/.github/workflows/update-version-header.yml
@@ -45,11 +45,13 @@ jobs:
           echo "sed -i 's/#define VERSION_PATCH [0-9]*/#define VERSION_PATCH '"$PATCH"'/' Source/ScooterUtils/Public/ScooterUtilsVersion.h"
           if [ $? -eq 0 ]; then echo "VERSION_PATCH updated successfully"; else echo "Failed to update VERSION_PATCH"; fi
 
-          echo "Version: $VERSION"
+          # build a multiplied version number for the uplugin file
+          MULTIPLIED_VERSION=$((MAJOR * 10000 + MINOR * 100 + PATCH))
+          echo "Multiplied Version: $MULTIPLIED_VERSION"
 
-          #echo "sed -i 's/"Version": [0-9]*.[0-9]*.[0-9]*/"Version": '"$VERSION"'/' ScooterUtils.uplugin"
-          #sed -i 's/"Version": [0-9]*\.[0-9]*\.[0-9]*/"Version": '"$VERSION"'/' ScooterUtils.uplugin
-          #if [ $? -eq 0 ]; then echo "uplugin Version updated successfully"; else echo "Failed to update uplugin Version"; fi
+          echo "sed -i 's/"Version": [0-9]*/"Version": '"$MULTIPLIED_VERSION"'/' ScooterUtils.uplugin"
+          sed -i 's/"Version": [0-9]*/"Version": '"$MULTIPLIED_VERSION"'/' ScooterUtils.uplugin
+          if [ $? -eq 0 ]; then echo "uplugin Version updated successfully"; else echo "Failed to update uplugin Version"; fi
 
           echo 'sed -i "s/\"VersionName\": \"v[0-9]*\.[0-9]*\.[0-9]*\"/\"VersionName\": \"v$VERSION\"/" ScooterUtils.uplugin'
           sed -i "s/\"VersionName\": \"v[0-9]*\.[0-9]*\.[0-9]*\"/\"VersionName\": \"v$VERSION\"/" ScooterUtils.uplugin
